pipeline {
    agent any

    stages {
        stage('Checkout code') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/Abdulbaasiterinkitola/alx-backend-python.git'
            }
        }

        stage('Set up Python') {
            steps {
                dir('alx-backend-python/messaging_app') {
                    sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run tests') {
            steps {
                dir('alx-backend-python/messaging_app') {
                    sh '''
                    . venv/bin/activate
                    pytest --junitxml=test-results.xml
                    '''
                }
            }
        }

        stage('Publish test results') {
            steps {
                dir('alx-backend-python/messaging_app') {
                    junit 'test-results.xml'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}
