pipeline {
    agent any

    stages {
        stage('Checkout code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Abdulbaasiterinkitola/alx-backend-python.git'
            }
        }

        stage('Set up Python') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r alx-backend-python/messaging_app/requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest alx-backend-python/messaging_app --junitxml=test-results.xml
                '''
            }
        }

        stage('Publish test results') {
            steps {
                junit 'test-results.xml'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}
