#!/usr/bin/bash
minikube delete --all
minikube start --memory=2800 --cpus=2
until kubectl get nodes | grep -m 1 'Ready'; do
    echo "Waiting for Minikube node to be ready..."
    sleep 2
done

echo "Minikube node is ready."
kubectl config use-context minikube

echo "Getting cluster info and services..."
kubectl cluster-info

echo "Listing all services in the cluster..."
kubectl get services

echo "Listing all pods in the cluster..."
kubectl get pods --all-namespaces
